### ISSUE TITLE
Documentation for  low-power_ek-tm4c123gxl is missing

### ISSUE THREAD

**Issue by acutetech** [QuantumLeaps/qpc#19]
The readme.MD for that example has a link to [documentation](https://www.state-machine.com/qpc/arm-cm_low-power.html)  which is broken. This link is also present at this [Sourceforge discussion](https://sourceforge.net/p/qpc/discussion/668726/thread/b7ef90d927/), which promises an application note on low power - does that AN exist?

**Comment by quantum-leaps** [comment]
The broken links to the ["low-power example"](https://www.state-machine.com/qpc/tut_low.html) in the [QP/C Manual](https://www.state-machine.com/qpc) have been fixed.
