### ISSUE TITLE
Incorrect code example

### ISSUE THREAD

**Issue by gbThreepwood** [QuantumLeaps/qpc#20]
https://github.com/QuantumLeaps/qpc/blob/20e4b27d13dc7926cd706f23b4b599f5e5ed1c8c/include/qf.h#L678

Documentation states that the code snippet should show "how to arm a one-shot time event from a state machine of an active object", however it only shows an example of a state which responds to timeout events.

**Comment by quantum-leaps** [comment]
The example at `qf.h:678` will be replaced with:

`static QState Game_show_logo(Tunnel * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /*.${AOs::Tunnel::SM::active::show_logo} */
        case Q_ENTRY_SIG: {
            /* arm periodic time event */
            QTimeEvt_armX(&me->blinkTimeEvt,
                          BSP_TICKS_PER_SEC/2U,  /* one-time delay */
                          BSP_TICKS_PER_SEC/2U); /* interval */
            /* arm a one-shot time event */
            QTimeEvt_armX(&me->screenTimeEvt,
                          BSP_TICKS_PER_SEC*5U,  /* one-time delay */
                          0U);      /* interval (0 == no interval) */
            . . .
            status_ = Q_HANDLED();
            break;
        }
        . . .
`
