### ISSUE TITLE
Undefined symbol assert_failed 

### ISSUE THREAD

**Issue by sichunqin** [QuantumLeaps/qpc#30]
I get "Undefined symbol assert_failed error" when I try to build the project "lesson-22-keil" with uvision 5.38.0.0 as followed: 
.\dbg\lesson.axf: Error: L6218E: Undefined symbol assert_failed (referred from startup_tm4c123gh6pm.o).

And get another error when I try to build "lesson-25-keil" with uvision 5.38.0.0:
miros_armclang.c(32): error: 'qassert.h' file not found

I already clone the qpc repository modern-embedded-programming-course folder and the 3rd_party repository under qpc folder, but still come cross the above error. Did I miss something to do?

**Comment by quantum-leaps** [comment]
Hi Sichun,
Thank you for your interest in the "Modern Embedded Systems Programming" course.

The project downloads for all lessons are now being extensively reorganized and updated. The earlier lessons (1-22) are mostly done (although things might still change). The later lessons (23-...) are still to be done, so please be patient.

Specifically, the newer versions of the QP/C framework (`qpc` directory) have been changed and therefore you see some compilation errors. All this will be fixed.

--MMS

**Comment by sichunqin** [comment]
Thanks for reply. I download qpc package from https://state-machine.com/quickstart, and rebuild the package. Then the project can be built successfully. 
BTW, your video course is wonderful, and appreciate very much for your great effort!
