### ISSUE TITLE
Can I use the quantum framework on a linux-like rtos (multi-process supported)?

### ISSUE THREAD

**Issue by andy27182** [QuantumLeaps/qpc#38]
Hi, I'm learning the quantum framework, and I found that all codes are compiled into the same executable file.

However, in actual scenarios, different businesses may be compiled into independent software.

Is it beneficial to compile `qpc` part into a dynamic library? And whether it will affect real-time performance in multi-process state.

-------------

I should actually ask the question in discussion, but I found that discussion has not been enabled, so I left the question in the issue.

**Comment by quantum-leaps** [comment]
Yes, you can,
--MMS
