### ISSUE TITLE
qpc 8.0 - qpc.h::Q_ALLEGE does not compile, while Q_UNSAFE is defined

### ISSUE THREAD

**Issue by stefanschober** [QuantumLeaps/qpc#43]
`Q_ALLEGE` as defined in `qpc.h` as:
`Q_onError(&Q_this_module_[0], (id_))`

`Q_this_module` is set via the `Q_DEFINE_THIS_..` macros in `qsafe.h`. If however `Q_UNSAFE` is defined, the macros expand to
`#define Q_DEFINE_THIS_MODULE(name_)`, which is a void definition. The symbol `Q_this_module_` will never be defined.

Best regards
Stefan

**Comment by quantum-leaps** [comment]
Fixed in the backward-compatibility layers (qpc.h and qpcpp.hpp) and pushed into the qpc and qpcpp repos.
--MMS
