### ISSUE TITLE
CMake updates to address changes in qpc 8.0.0

### ISSUE THREAD

**Issue by stefanschober** [QuantumLeaps/qpc#44]
- `cmakeSupport.md` updated
- `ports/CMakeLists.txt` updated to address mandatory inclusion of `qp_config.h`
- `src/qs/CMakeLists.txt` updated to address new license definitions

[qpc.diff.zip](https://github.com/user-attachments/files/17568502/qpc.diff.zip)

**Comment by quantum-leaps** [comment]
Merged and pushed into the qpc repo.
Thank you,
--MMS
