### ISSUE TITLE
Possible issue in arm-cr interrupt enable/disable code?

### ISSUE THREAD

**Issue by robbel** [QuantumLeaps/qpc#46]
In the arm-cr port for GNU (e.g., this [qp-port.h](https://github.com/QuantumLeaps/qpc/blob/master/ports/arm-cr/qv/gnu/qp_port.h)), the following macros are defined for interrupt enable/disable in the case of ARM mode:

```
    #define QF_INT_DISABLE()   \
        __asm volatile ("MSR cpsr_c,#(0x1F | 0x80)" ::: "cc")
    #define QF_INT_ENABLE() \
        __asm volatile ("MSR cpsr_c,#(0x1F)" ::: "cc")
    #define QF_INT_ENABLE_ALL() \
        __asm volatile ("MSR cpsr_c,#(0x1F | 0x80 | 0x40)" ::: "cc")
```

Is the last definition correct?  That looks to me as if it is trying to disable, rather than enable, IRQ and FIQ interrupts by setting the respective bits (i.e., closer in semantics to a `QF_INT_DISABLE_ALL`).  Since FIQ interrupts are never disabled in the arm-cr port, such a macro may not make sense?

**Comment by quantum-leaps** [comment]
Good catch. The code has been corrected and pushed into the qpc and qpcpp repos.

This issue exists only in the GNU compiler port and only in ARM mode. In the examples, the initialization code has always been compiled in THUMB mode (why use ARM mode for that?), so the bug went unnoticed.

However, bug is a bug and thank you for reporting,
--MMS
