### ISSUE TITLE
gnu examples are not using nano

### ISSUE THREAD

**Issue by jwinarske** [QuantumLeaps/qpc#5]
You can considerably shrink the size of the GNU binaries in the example projects, by this simple change:

In all references of:

	-specs=nosys.specs \

Change to:

	-specs=nosys.specs -specs=nano.specs \

**Comment by quantum-leaps** [comment]
Thanks for the tip. The savings seem to be of the order of 250 bytes for QP/C applications and some 700 bytes for QP/C++ applications. This is worthwhile. The changes will be added to the Makefiles for GNU-ARM in QP/C/C++/nano.
--Miro
